### PR TITLE
Add conditional display

### PR DESCRIPTION
**Pull request by LeGfrey**
## Intro
Hi, I'm developing this to help people (like me) encountering the _issue_ [with conditional display](https://github.com/space10-community/conversational-form/issues/18).

So my solution is a bit different since my last post.

I decided to create an attribute `cf-display-if` which can take something like this.
* `NAME_OF_AN_INPUT_TAG == 'value1' AND NAME_OF_AN_INPUT_TAG == 'value2'`
* `NAME_OF_AN_INPUT_TAG == 'value1' OR NAME_OF_AN_INPUT_TAG == 'value2' AND NAME_OF_AN_INPUT_TAG == 'value3'`
* `NAME_OF_AN_INPUT_TAG CONTAINS ('value1')`

Then this syntax is parsed to a javascript expression which will be evaluated when a tag containing this attribute is displayed.

## How can I test this feature ? 

If you want to test it and see if it works I created an example here on pastebin.
Just build CF from sources and copy paste this [pastebin](http://pastebin.com/ugYqCA1S) on **/test/custom-form.html**

*I also upload an example online right here : http://cf-conditional.surge.sh/*
Thanks to awesome surge service.

## What's next ? 
If you agree with my solution, want some information, or want modifications on it. Please post a comment and I'll try to answer you as fast as I can.
When/If my modification is ready to be merged I'll be glad to write more documentation (about the syntax) on the readme.

Thanks in advance.

### CODE REVIEW

**Comment by LeGfrey** [comment]
@AlienFX You're welcome.
Concerning your problem did you install typings ?
``` bash
$ cd src/scripts
$ typings install
```

**Comment by iamtheream** [comment]
Thanks @LeGfrey this works very well.

**Comment by SlimJB** [comment]
Hey guys,
I'm implementing Conversational Form on a website, and to be honest Javascript is not specialty at all. I want to create a conditional form using the <option> fields to display (or not) the following questions. I've tried the best I can for hours, but I will soon have not more hairs to pull out, so if someone could help me, this would be wonderful!
Thanks!

**Comment by maringerov** [comment]
Hey there :) Is there a chance to get this feature merged soon? I also want to use it in a project :) Great work!!!

**Comment by LeGfrey** [comment]
Any news from the maintainers ? 😄

**Comment by felixnielsen** [comment]
@LeGfrey @maringerov Yes!:) a very similar feature will be released thursday. Looking forward to your feedback on it!

**Comment by maringerov** [comment]
@felixnielsen @LeGfrey Great stuff! Thanks! Looking forward :)

**Comment by felixnielsen** [comment]
@LeGfrey @maringerov Please have a look at branch [conditional-flow](https://github.com/space10-community/conversational-form/tree/conditional-flow), have a look at examples/development.html and the [WIP documentation](https://github.com/space10-community/conversational-form/wiki/Conditional-Flow) for insights

**Comment by sull** [comment]
@felixnielsen So great job on Conditional Flow. Just to be sure, can you clarify if this can handle not just showing tag within existing flow but also jumping to the tag(s) that are mapped to the condition (if not sequentially next in the form markup or formless json data)? I don't think so but have not scanned all code. I suppose it is not that hard to just make sure the questions are in a sequence that makes it work close to free form jumping.

Maybe a different enhancement would be forward commands rather than referencing backwards to previous answers meeting conditions.

So something like:

`<input type="radio" name="cfc-intro" id="intro-yes" value="yes" cf-jump-cfc-outro="yes">`

This cf-jump command would essentially let you take a user throughout a set of questions in any arbitrary manner but of course it would be designed logically by form creator. Maybe for it to work well with `cf-conditional` the jump would not go to a specific field tag and rather jump to a fieldset tag where `cf-conditional` could take over and display only applicable fields based on previous answers.

**Comment by felixnielsen** [comment]
@sull interesting feature! `cf-jump` could be a mix between current functionality `edit`, if the step one wants to jump to is already in the context and an actual `gotoStep` (which is already functional code), I'll have a think and a chat with @danielfriis on monday about this feature, would be a great addition I think it, at least as a underlying feature.

**Comment by sull** [comment]
I will need to review `gotoStep` because thus far I have only been bouncing around different issue discussions and skimming code and running some initial tests of the code (conditional-flow branch using formless method). Maybe my idea is redundant but still a useful variation. Look forward to chatting more about it next week. Thanks for response.

**Comment by sull** [comment]
Any more thoughts on this approach (cf-jump)?

**Pull request closed without merging**
