### PR TITLE
Pre v0.9.3 — formless feature

### PR DESCRIPTION
**Pull request by felixnielsen**
See examples/formless.html

### CODE REVIEW

**Comment by Doss12** [comment]
Hello , i want to ask you why in formless the children have the same id
Here is my JSON , the two childrens have "seeaccount" id.

formFields = [
  {
    "tag": "fieldset",
    "type": "Radio buttons",
    "cf-input-placeholder": "Hello , how can i help you",
    "cf-questions": "Hello , how can i help you ? ",
    "isMultiChoice": false,
    "children": [
      {
        "tag": "input",
        "id": "seeaccount",
        "type": "radio",
        "name": "see_accounts",
        "value":"accounts",
        "cf-label":"See Accounts" 
      },
      {
        "tag": "input",
        "id": "TransferMoney",
        "type": "radio",
        "name": "see_accounts",
        "value":"transfer",
        "cf-label": "Transfer Money"
      },
    ]
  }
];

Thanks in advance.

**Comment by jenssogaard** [comment]
@Doss12 I would skip the id and just use `name`. It does not seem beneficial to use the same ID across elements.

**Comment by Doss12** [comment]
I changed my JSON like that : 
```

formFields = [

  {
    "tag": "select",
    "cf-input-placeholder": "Hello , how can i help you",
    "cf-questions": "Hello , how can i help you ? ",
    "isMultiChoice": false,
    "children": [
      {
        "tag": "option",
        "name": "seeaccounts",
        "cf-label":"See Accounts" 
      },
      {
        "tag": "option",
        "name": "transfermoney",
        "cf-label": "Transfer Money"
      },
      {
        "tag": "option",
        "name": "externalaccount",
        "cf-label":"Add New External Account" 
      },
    ]
  },
];
```

but the problem persists cause all options have the same name as the first option ("seeaccounts") in onFlowBack function

**Comment by jenssogaard** [comment]
@Doss12. Can't you use [`cf-conditional`-syntax](https://space10-community.github.io/conversational-form/docs/0.9.90/functionality/conditionals-and-branching/)?

Is your problem that the form stops/ends after the first dynamically added question?

**Comment by Doss12** [comment]
Sorry i changed the code yesterday and forgot to put it back , could you please see again the codepen ? the problem is whether i click on see Account or Transfer money , i have the same response cause the conversational form doesn't attribute the name i specified in the option tag .As a result , the two options have the same name ( the name of the first option)

**Comment by jenssogaard** [comment]
Hi @Doss12 I have tweaked your code. Specifically:
`switch(dto.tag.value[0]){`

and

```
"children": [
            {
                "tag": "option",
                "name": "action",
                "value": "seeaccounts",
                "cf-label": "See Accounts"
            },
            {
                "tag": "option",
                "name": "action",
                "value": "transfermoney",
                "cf-label": "Transfer Money"
            },
        ]
```

[Link for the forked codepen.](https://codepen.io/jens-s-gaard/pen/NZJgGw?editors=0011)

This should be able to help you move forward.

**Comment by Doss12** [comment]
I tried to do this before but imagine the case when you want to put an account id in Value , it becomes too difficult to manage the flow especially when you have to many accounts ! i found out that the solution to this is to declare the option tag like this : 
 ````
  {
            "tag": "input",
            "type": "radio",
            "value":JSON.stringify({
              "type":"seeaccounts",
              "value":accoundId }),
            "cf-label": "See Account"
          }
```
And in onFlowBack function i did  switch((JSON.parse(dto.tag.value[0])).type)

**Comment by jenssogaard** [comment]
@Doss12 sounds like a good solution.

**Pull request merged**
