### PR TITLE
Changes in style files structure and add !default to variables (fix #219)

### LINKED ISSUE #219: Include !default on your SASS variables and include main .scss file
Hi,
I have a project where I imported `conversational-forms` using NPM and the Webpack module bundler. I would like to customize the appearance by customizing the SASS variables, importing your project's SASS files into my codebase and setting `loadExternalStyleSheet` to `false`. However, there is a big problem with your SASS files. I cannot overwrite the variables because they are loaded via an `@import` inside your `src/styles/cf/cf.scss` (a file that needs to be included) and the variables themselves are not overridable by the [`!default` option](http://sass-lang.com/documentation/file.SASS_REFERENCE.html#variable_defaults_default). It would be truly great if the variables could be overriden.
Another nice addition to your project for this use case would be a main .scss file which would import all the required files. This way, when a user wanted to load all the .scss files into their own project, they would only need to `@import` a single .scss file which would then load all the required partials. This would be way more handy, and it would also have the advantage of not having to manually check the dependencies on project updates. This file could also be the entry point for your Gulp building routine.
Thanks for your time :)
Jordi

### PR DESCRIPTION
**Pull request by jorditarrida**
These changes allow for SASS variables to be overriden. They also allow for easy SASS importing to other projects by just using the new `main.scss` file. The Gulp tasks have also been updated to reflect these changes.

### CODE REVIEW

**Comment by jenssogaard** [comment]
@jorditarrida I'm looking through and testing the PR now. Everything works as intended 🔥 💥 👍 . 
One minor thing: I think it makes more sense to name _main.scss_ --> _ConversationalForm.scss_ to keep consistency with JS and naming throughout the rest of the project, agree?

Also, can you change CSS imports in the src/development*.html to reflect the single .css. Current:
`<link type="text/css" rel="stylesheet" href="../build/cf/cf.css"/>
<link type="text/css" rel="stylesheet" href="../build/cf/ui/control-elements/cf-control-elements.css"/>
<link type="text/css" rel="stylesheet" href="../build/cf/ui/control-elements/cf-button.css"/>
<link type="text/css" rel="stylesheet" href="../build/cf/ui/control-elements/cf-radio-button.css"/>
<link type="text/css" rel="stylesheet" href="../build/cf/ui/control-elements/cf-checkbox-button.css"/>
<link type="text/css" rel="stylesheet" href="../build/cf/ui/control-elements/cf-options-list.css"/>
<link type="text/css" rel="stylesheet" href="../build/cf/ui/control-elements/cf-upload-file-ui.css"/>
<link type="text/css" rel="stylesheet" href="../build/cf/ui/cf-input.css"/>
<link type="text/css" rel="stylesheet" href="../build/cf/ui/cf-info.css"/>
<link type="text/css" rel="stylesheet" href="../build/cf/ui/cf-list-button.css"/>
<link type="text/css" rel="stylesheet" href="../build/cf/ui/chat/cf-chat-response.css"/>
<link type="text/css" rel="stylesheet" href="../build/cf/ui/chat/cf-chat.css"/>`

to: `<link type="text/css" rel="stylesheet" href="../build/main.css"/>`

If that is fixed I believe we are ready to merge your PR and release an update along with a few other things in the works.

**Comment by jorditarrida** [comment]
Hi,
I am renaming it to conversational-form.scss if you're OK with it (consistency with the naming in the generated `dist/` folder). Will push in a few minutes.
Cheers,
Jordi

**Comment by jorditarrida** [comment]
Done! Please do let me know if you need anything else.
Cheers,
Jordi

**Comment by jenssogaard** [comment]
@jorditarrida awesome, thank you. I'm merging tonight and doing some other minor scss touch-ups while I'm at it.

**Pull request merged**
