### PR TITLE
Fix typos.

### PR DESCRIPTION
**Pull request by seanhussey**

### CODE REVIEW

**Comment by seanhussey** [comment]
I think the CI failures are unrelated to the change.

**Comment by jenssogaard** [comment]
Hi @seanhussey. Thank you for taking the time to do a PR. We really appreciate it. Since your PR we have redone our README. If you still feel like doing a PR then please do it agains the develop branch : https://github.com/space10-community/conversational-form#contributing

**Comment by seanhussey** [comment]
Will do. I'll remake the changes against the correct branch. I apologize for not following the contribution guidelines.

**Comment by seanhussey** [comment]
Closing this in preference to #208.

**Pull request closed without merging**
